project:
  type: website
  pre-render: "echo Let the rendering begin!"
  # post-render: "Rendering done!"

website:
  title: "Various notes about R"
  repo-url: https://github.com/mathiaslj/R_notes
  repo-actions: [source]
  back-to-top-navigation: true
  bread-crumbs: false
  navbar:
    left:
      - sidebar:data-wrangling
      - sidebar:plotting
      - sidebar:pkg-dev
      - sidebar:prog
    right: 
      - icon: github
        href: https://github.com/mathiaslj/R_notes
      
  sidebar: 
    - id: data-wrangling
      title: Data wrangling
      style: "docked"
      collapse-level: 1
      contents:
        - section: "Base R"
          contents:
            - data-wrangling/baser.qmd
        - section: "The tidyverse"
          contents:
            - data-wrangling/tidyverse.qmd
    - id: plotting
      title: Plotting
      style: "docked"
      collapse-level: 1
      contents:
        - section: "Principles of Effective Data Visualisation"
          contents:
            - plotting/edv.qmd
        - section: "Creating plots"
          contents:
            - plotting/colors-in-R.qmd
            - plotting/grid-and-gggrid.qmd
            - plotting/ggplot2.qmd
            - plotting/maps.qmd
        - section: "Animation and interactivity"
          contents:
            - plotting/animation.qmd
            - plotting/interactivity.qmd
        - section: "SVG Graphics"
          contents:
            - plotting/svg.qmd
    - id: pkg-dev
      title: Package development
      style: "docked"
      collapse-level: 1
      contents:
        - section: "Creating a package"
          contents:
            - pkg-dev/get-started.qmd
            - pkg-dev/gh-actions.qmd
            - pkg-dev/cran.qmd
    - id: prog
      title: Programming in R
      style: "docked"
      collapse-level: 1
      contents: 
        - section: "Functional programming"
          contents:
            - prog/func_prog.qmd
        - section: "Object-oriented programming"
          contents:
            - prog/obj_prog.qmd
        
format:
  html:
    theme: 
      - flatly
      - styles.scss
    toc: true