---
title: "Colors and text in R"
format: html
---

# Colours

See [Color Pitfalls](edv.qmd#sec-colorpitfalls) on this webpage.

The [colorspace](https://colorspace.r-forge.r-project.org/index.html) package can be used to A LOT of things. Examples:

- [Desaturating the color of some categories in a ggplot](https://mathiaslj.github.io/stats787uoa-data-visualisation/labs/lab4_answer.html#question-4)
- [Testing for color vision deficiency](https://mathiaslj.github.io/stats787uoa-data-visualisation/labs/lab4_answer.html#question-5)
- [Non-linear pallette scaling](https://mathiaslj.github.io/stats787uoa-data-visualisation/labs/lab9_answer.html#creating-non-linear-colour-scales)

# Text

See package [ggtext](https://wilkelab.org/ggtext/) for ways to fx. color text labels, titles, etc. based on categories in data.

- Just specify the text using HTML code and specify the relevant argument in `ggplot2::theme()` using the function [`ggtext::element_markdown()`](https://wilkelab.org/ggtext/reference/element_markdown.html).
  - See an example of [how to color your title](https://mathiaslj.github.io/stats787uoa-data-visualisation/labs/lab5_answer.html#question-3) in question 3 of lab5 at UoA.

See also [gridtext](https://wilkelab.org/gridtext/) for text rendering support for grid graphics in R.

## Fonts

See [Fonts in R](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Notes/Fonts/fonts-notes.html) for a small introduction

### Getting new fonts

Download font online: 

1) Go to font download site, fx. [Google Gruppo](https://fonts.google.com/specimen/Gruppo?category=Serif,Display,Handwriting,Monospace)
2) Click download
3) When downloaded, extract it
3a) On windows, click the `Gruppo-regular` file and press "Install"
4) In R, use the cairo graphics device
4a) In Rstudio: Tools -> Global options -> General -> Graphics (top) -> Backend -> Choose cairo
4b) In Rmarkdown: Include `knitr::opts_chunk$set(dev.args = list(png = list(type ="cairo")))` in setup chunk.
5) Refer to the new font by it's folder name in your system. Fx. `ggplot2::element_text(family = "Gruppo")`

# References

- ["Selecting colours in R"](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Notes/Colour/colour-notes.html)
  - Various R functions to generate colors
- The [Colorspace](https://colorspace.r-forge.r-project.org/index.html) R package
  - "A Toolbox for Manipulating and Assessing Colors and Palettes"
- [“Coloring in R’s Blind Spot”](https://arxiv.org/abs/2303.04918)  by Achim Zeileis and Paul Murrell
  - A walkthrough of new R color and palette functions introduced with R version 4.0.0

**Practical advice on how to use colors most "efficiently" in your plots**

- Chapters [4](https://clauswilke.com/dataviz/color-basics.html) and [19](https://clauswilke.com/dataviz/color-pitfalls.html) of “Fundamentals of Data Visualization” by Claus O. Wilke.