---
title: "Plot design - CRAP principles and fonts"
format: html
---

# CRAP design principles

The [“The Non-Designer’s Design Book”](https://www.pearson.com/en-us/subject-catalog/p/non-designers-design-book-the/P200000000691?view=educator) by Robin Williams proposes four major design features that make an image more appealing and more effective: Contrast, Repetition, Alignment, and Proximity (CRAP).

See [lecture notes about CRAP principles](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Topics/design.html) for more information about the meaning of the 4 design features. Below are short quotes about each principle from the link.

- **Contrast:** Elements of an image should be either very similar or very different. If elements of an image are supposed to be different, make them obviously different.
  - See [these slides](https://datavizm20.classes.andrewheiss.com/slides/02-slides.html#21) by Andrew Heiss.
- **Repitition:** Specific colours or styles should be used to tie elements of an image together. This helps to create a more consistent, more cohesive, less chaotic, image.
  - Fx. within an image by making all text have same color/size/... or across images in a report
- **Alignment:** All elements of an image should be aligned with some other anchor point in the image. This helps to create organisation and structure within an image, which can make it easier to navigate within the image.
  - Fx. aligning the legend vertically with the top of the plotting region, aligning the title with the left of the plotting region, etc.
  - See [example](https://datavizm20.classes.andrewheiss.com/slides/02-slides.html#48) in slides by Andrew Heiss of a compound figure.
- **Proximity:** Elements of an image should be placed close to each other to form sub-elements of the image.
  - Fx. moving axis breaks closer to axis ticks or moving keys in a legend closer together to highlight that they "belong together"
  
See also much more information in the readings in the link to lecture notes.

# Fonts

