---
title: "Effective Data Visualisation and Visual Perception"
---

## Concepts from [sections 1.1 and 1.2](https://socviz.co/lookatdata.html#why-look-at-data) of *“Data Visualization: A practical introduction”* by Kieran Healey.

- **Aesthetic:** Ugly or inconsistent design choices
- **Substantive:** It's not about making stuff look pretty but making sure to present data in the most informative way.
  - In many cases, this is not an issue directly with the plot but with the data. Always related to our question of interest.
- **Perceptual:** In these cases, even with good aesthetic qualities and good data, the graph will be confusing or misleading because of how people perceive and process what they are looking at. 
  - Fx. a continuous color scale for many categories can make it hard to distinguish colors from each other and can make fx. make a color appear lighter than it actually is if surrounded by darker colors.
- **Data-to-ink ratio (concept by Tufte):** Tufte proposes to always maximise the data-to-ink ratio. Only add ANYTHING if it is really, really needed
  - Healey notes that *..., it may be the case that graphics that really do maximize the data-to-ink ratio are harder to interpret than those that are a little more relaxed about it*.

## [The principle of proportional ink](https://clauswilke.com/dataviz/proportional-ink.html)

This concept has been termed by Bergstrom and West as the principle of proportional ink (Bergstrom and West [2016](https://callingbullshit.org/tools/tools_proportional_ink.html)):

> **The principle of proportional ink:** The sizes of shaded areas in a visualization need to be proportional to the data values they represent.

- Most plots should always include 0 in the y-axis.
  - Be careful with heights/widths of bars.
- If values in a plot are much different from 0, making it hard to see differences, consider changing the response to a difference of some sort.
- On logarithmic axes, bars are a ratio. Make sure to represent correctly.
  - Consider using points instead of bars.

## [Direct Area Visualisations](https://clauswilke.com/dataviz/proportional-ink.html#direct-area-visualizations)

> *"..., we perceive the area in a pie chart differently from the same area in a bar plot. The fundamental reason is that human perception primarily judges distances and not areas. Thus, if a data value is encoded entirely as a distance, as is the case with the length of a bar, we perceive it more accurately than when the data value is encoded through a combination of two or more distances that jointly create an area."*

Functions to change the scale of point sizes (when using `aes(size = xx)` in a `geom_point` fx.):
- `ggplot2::scale_radius` can be used to scale based on radius rather than area since.
- `ggplot2::scale_size_area` can be used to make sure ratio of sizes is equal to ratio of data values.

**Note!** Above function are generally not recommended, as they break with the principle of proportional ink. However, still might be cases where it makes sense to do.

## [Overplotting](https://clauswilke.com/dataviz/overlapping-points.html)

**Issue:** points that overlap.

**Possible fixes:**
- Transparent points
- Jitter
- High density of points: *Use 2D histogram*
  - See `ggplot2::geom_bin2d` and `ggplot2::geom_hex` (hexagons are more "correct")
  - See also `smoothScatter` in the base `graphics` package, whic makes a 2D kernel density estimate but also shows points "on the edge".
- Contour lines
  - See `ggplot2::geom_density2d` or `ggplot2::geom_density2d_filled`
    - Be wary of `ggplot2::geom_density2d` not showing the entire range of data

## [Color pitfalls](https://clauswilke.com/dataviz/color-pitfalls.html) {#sec-colorpitfalls}

- Encoding too much or irrelevant information
  - Too much:
    - **Quote from reference in title:** *"As a rule of thumb, qualitative color scales work best when there are three to five different categories that need to be colored. Once we reach eight to ten different categories or more, the task of matching colors to categories becomes too burdensome to be useful, even if the colors remain sufficiently different to be distinguishable in principle."*
    - **Possible solutions**: Label points (potentially color according to a categorisation variable with fewer levels while labelling according to the variable of interest)
  - **Irrelevant:** Do not color without a clear purpose that helps answer a question.

### Color vision deficiency

**Tip:** To make sure your figures work for people with *cvd (color-vision-deficiency)*, don’t just rely on specific color scales. Instead, test your figures in a cvd simulator
- See [`colorspace::deutan`](https://colorspace.r-forge.r-project.org/reference/simulate_cvd.html)

### Color contrasts

We judge color relative to other colors, so colors might appear darker or lighter than they are depending on surrounding colors. See fx. [section 1.3.1](https://socviz.co/lookatdata.html#perception-and-data-visualization) from Kieran Healy.

### Color "scales"

See [slide 11](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Slides/perception-slides.html#/colour).

Works for categorical variables:

- *hue:* Different colors

Works for numerical variables:

> Make sure to keep hue constant while changing these.

- *chroma:* How "saturated" the color is. White, grey, black have no chroma.
- *luminance:* Darkness/brightness of color. On scale we go from white to black.

### It's not only about color

[Redundant coding](https://clauswilke.com/dataviz/redundant-coding.html) in essence means we do more than one aesthetic mapping to a single variable. Wilke fx. recommends:

> *"use color to enhance the visual appearance of the figure without relying entirely on color to convey key information."* 

- **Scatter plots:** Fx. change the shape of points instead of only color.
- **Line plots:**
  - Changing line type often **does not work very well**. 
  - *"If there is a clear visual ordering in your data, make sure to match it in the legend."*.
    - Most plots will create legend in alphabetical order. Make sure to create factor with levels ordered by magnitude.
    
## [Designing figures without legends](https://clauswilke.com/dataviz/redundant-coding.html#designing-figures-without-legends)

> *"Whenever possible, design your figures so they don’t need a legend."*

See packages:
- `ggforce` which has `geom`s that take `label` as an aesthetic mapping
- `directlabels`

## [Multi-panel figures](https://clauswilke.com/dataviz/multi-panel-figures.html)

- **Small multiples:** *"Small multiples are plots consisting of multiple panels arranged in a regular grid. Each panel shows a different subset of the data but all panels use the same type of visualization."*
  - Be **very careful** with having different axis ranges across panels. Guideline to almost never do this. If you HAVE to, make a note about it to the reader.
- **Coumpound figures:** *"Compound figures consist of separate figure panels assembled in an arbitrary arrangement (which may or may not be grid based) and showing entirely different visualizations, or possibly even different datasets."*
  - Unlike small multiples, where panels are labelled by variables, labels often need to **be added manually** to compound figures. Make sure they uniquely define each figure and are formatted (font, size, placement, etc.) nicely.
  
## [Titles, captions and tables](https://clauswilke.com/dataviz/figure-titles-captions.html)

- **Title:** *"Either the title is integrated into the actual figure display or it is provided as the first element of the caption underneath the figure."*
  - Use `title`, `subtitle` and `caption` in `labs`.
- **Axis and legend titles:**
  - Axis and legend titles should be informative. 
    - Display units in parentheses when possible.
  - Legend label not needed when self explanatory. Fx. when values displayed are "female" and "male", so the variable is obviously sex/gender.
- **Tables:**
  - See the 6-item breakdown of table guidelines in [this section](https://clauswilke.com/dataviz/figure-titles-captions.html#tables) from the reference in the title of this section.
  - Place captions on top (underneath for figures).
  
**Tip:** Use `expression`s to make LaTeX rendered text. Fx. write
```{r, eval = FALSE}
labs(x = expression(paste("Engine displacment (", "in"^3, ")")))
```

to render the exponent.

## [Gestault rules](https://socviz.co/lookatdata.html#gestalt-rules)

> *"The strong inferences we make about relationships between visual elements from relatively sparse visual information are called “gestalt rules”. They are not pure perceptual effects... Rather, they describe our tendency to infer relationships between the objects we are looking at in a way that goes beyond what is strictly visible..."*.

See [slide 10](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Slides/perception-slides.html#/gestalt-rules) for a "ranking" of what rules are dominant over each other and should be used for creating relations between data values.

## Channels

*Channels* are a concept from [section 1.5](https://socviz.co/lookatdata.html#channels-for-representing-data) from Kieran Healey. See a list of visual channels in the figures to the right in the reference.

Order of "best" channels, where "best" means that randomly asked people can best decode the value of data from a visualisation.

- Position
- Length
- Angle
- Area
- Color
- Shape
- Texture (fx. hashing areas)
  - Usually just a worse choice than color

# References

## Lecture notes and slides from [STATS 787: Data Visualisation at UoA](https://courseoutline.auckland.ac.nz/dco/course/STATS/787/1213)

- [Lecture 1 (Introduction to Data Visualisation)](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Topics/intro.html)
  - [Slides](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Slides/intro-slides.html#/)
- [Lecture 4 (Effective Data Visualisations)](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Topics/effective.html)
  - [Slides](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Slides/effective-slides.html#/)
- [Lecture 5 (Visual Perception)](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Topics/perception.html)
  - [Slides](https://www.stat.auckland.ac.nz/~paul/stats787/Current/Slides/perception-slides.html#/)


## References from inside lecture notes

- **Top tier book!!** *"[Fundamentals of Data Visualization](https://clauswilke.com/dataviz/)"* by Claus O. Wilke
- *"[Data Visualization: A practical introduction](https://socviz.co/lookatdata.html#why-look-at-data)"* by Kieran Healey.